# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestPodDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'WGBPackFramework' , :path => './MyFramework'
  # Pods for TestPodDemo

end
